[package]
name = "zelll"
authors = ["Vincent Messow <vincent.messow@uni-jena.dde>"]
repository = "https://github.com/microscopic-image-analysis/zelll"
readme = "README.md"
license = "MIT"
description = "tbd."
include = ["src/*", "Cargo.toml", "README.md", "COPYING"]
keywords = []
categories = ["science"]
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nalgebra = "0.31"
ndarray = "0.15"

[features]
default = []
rayon = ["ndarray/rayon"]