[package]
name = "zelll"
authors = ["Vincent Messow <vincent.messow@uni-jena.de>"]
repository = "https://github.com/microscopic-image-analysis/zelll"
readme = "README.md"
license = "MIT"
description = "tbd."
include = ["src/*", "Cargo.toml", "README.md", "COPYING"]
keywords = []
categories = ["science"]
version = "0.1.0"
edition = "2018"

[dependencies]
itertools = "0.10"
nalgebra = "0.30"
hashbrown = "0.13"
rayon = {version = "1.0", optional = true}

[dev-dependencies]
kiss3d = "0.35"
nalgebra = { version = "0.30", features = ["debug"] }
soa_derive = "0.12"
dashmap = "5.4"

[features]
default = []
rayon = ["dep:rayon", "hashbrown/rayon"]